name: sunpy-rtd
channels:
    - conda-forge
dependencies:
  - python=3.5
  - numpy
  - cython
  - matplotlib
  - scipy
  - pillow
  - pyyaml
  - jinja2
  - h5py
  - scikit-image
  - pandas
  - pytz
  - beautifulsoup4
  - mpmath
  - astropy
  - sphinx
  - sphinx_rtd_theme
  - glymur
  - sphinx-gallery
  - sqlalchemy
  - suds-jurko
  - pip:
      - sunpy-sphinx-theme
