language: minimal

os:
    - linux

stage: Initial tests

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

branches:
  except:
    - /^auto-backport-of-pr-[0-9]+$/

# The apt packages below are needed but can no longer be installed with
# sudo apt-get.
addons:
    apt:
        packages:
            - libopenjpeg5
            - graphviz

# Configure the build environment. Global variables are defined for all configurations.
env:
    global:
        - COLUMNS=180
        - PYTHON_VERSION=3.6
        - PREVIOUS_NUMPY=1.13.3
        - NUMPY_VERSION='stable'
        - ASTROPY_VERSION='stable'
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test --coverage'
        - CONDA_CHANNELS='sunpy'
        - CONDA_DEPENDENCIES='openjpeg Cython jinja2 scipy matplotlib mock requests beautifulsoup4 sqlalchemy scikit-image pytest-mock lxml pyyaml pandas pytest-astropy suds-jurko glymur dask drms sphinx sphinx-astropy pytest-cov hypothesis'
        - PIP_DEPENDENCIES='pytest-sugar'
        - EVENT_TYPE='push pull_request cron'
        - MPLBACKEND='agg'
        - JOB='test'
        - PYTEST_VERSION='<3.7'

matrix:

    # Don't wait for allowed failures
    fast_finish: true

    include:
         # We order the jobs, in terms of the maintainers mood
         # Order of tests run in build stages
         # Python 2.7 (implicit Astropy 2)
         - python: 2.7
           env: SETUP_CMD='test' PYTHON_VERSION=2.7

         - python: 3.5
           env: SETUP_CMD='test'

         - python: 3.6
           env: SETUP_CMD='test'

         - python: 3.7
           env: SETUP_CMD='test'

        # Comprehensive tests below this line

         # Figure test runs use an env stored in the repo so don't have conda
         # requirements
         # Python 2.7 figure tests
         - python: 2.7
           env: SETUP_CMD='test --figure-only ' CONDA_DEPENDENCIES='' PYTHON_VERSION=2.7

         # Python 3.5 figure tests
         - python: 3.5
           env: SETUP_CMD='test --figure-only ' CONDA_DEPENDENCIES='' PYTHON_VERSION=3.5

         # Python 3.5 with Astropy 2
         - python: 3.5
           env: ASTROPY_VERSION='lts' PYTHON_VERSION=3.5

         - os: osx
           language: generic
           env: PYTHON_VERSION=3.6

         - python: 3.6
           env: ASTROPY_VERSION='dev'

install:
    - git clone --depth 1 git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

before_script:
    # Download the sample data for the online builds only.
    - if [[ $SETUP_CMD == *online-only* ]] || [[ $SETUP_CMD == *remote-data* ]] || [[ $PYTHON_VERSION == "2.7" ]]; then python -m "sunpy.data.sample"; fi
    - if [[ $MAIN_CMD == py.test* ]]; then pip install -e ./; fi
    - if [[ $SETUP_CMD == *figure* ]]; then conda env create --file sunpy/tests/figure_tests_env_$PYTHON_VERSION.yml; source activate sunpy-figure-tests-$PYTHON_VERSION; fi
    - if [[ $JOB == *pip* ]]; then pip install .[all]; fi

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD = *"cov"* ]]; then pip install codecov; codecov; fi

# Notify the IRC channel of build status
notifications:
  webhooks:
    urls:
      - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MENhZGFpciUzQW1hdHJpeC5vcmcvJTIxTWVSZEZwRW9uTG9Dd2hvSGVUJTNBbWF0cml4Lm9yZw"
    on_success: change  # always|never|change
    on_failure: always
    on_start: never
