variables:
  Agent.Source.Git.ShallowFetchDepth: 1
  CI_NAME: Azure Pipelines
  CI_BUILD_ID: $(Build.BuildId)
  CI_BUILD_URL: "https://dev.azure.com/sunpy/sunpy/_build/results?buildId=$(Build.BuildId)"

jobs:
- template: azure-templates.yml
  parameters:
    name: Linux_37_online
    os: linux
    tox: py37-online -- -n=4
    python: '3.7'

- template: azure-templates.yml
  parameters:
    name: Windows_27_offline
    os: windows
    tox: py27-offline --
    python: '2.7'

- template: azure-templates.yml
  parameters:
    name: Windows_36_offline
    os: windows
    tox: py36-offline --
    python: '3.6'
