jobs:
- job: ${{ format(parameters.name) }}
  pool:
    ${{ if eq(parameters.os, 'windows') }}:
      vmImage: vs2017-win2016
    ${{ if eq(parameters.os, 'macos') }}:
      vmImage: macOS 10.13
    ${{ if eq(parameters.os, 'linux') }}:
      vmImage: Ubuntu 16.04

  steps:

  - checkout: self
    submodules: false

  - ${{ if eq(parameters.os, 'linux') }}:
    - script: |
        sudo apt-get install -y libopenjpeg5
      displayName: apt install openjpeg

  - ${{ if eq(parameters.os, 'macos') }}:
    - script: |
        brew install openjpeg
      displayName: brew install openjpeg

  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{ parameters.python }}

  - script: pip install --upgrade tox
    displayName: install tox

  - ${{ if contains(parameters.tox, 'conda') }}:
    - script: pip install --upgrade tox-conda
      displayName: install tox-conda

  - script: tox -e ${{ parameters.tox }} -vvv
    displayName: run tox
