name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
      - 2.0
    always: true

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: sunpy
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
    exclude:
    - '*backport*'
  tags:
    include:
    - 'v*'
    exclude:
    - '*dev*'
    - '*pre*'
    - '*post*'

jobs:
- template: run-tox-env.yml@OpenAstronomy
  parameters:
    default_python: '3.8'
    submodules: false
    coverage: codecov
    toxdeps: tox-pypi-filter
    posargs: -n=4
    libraries:
      apt:
        - libopenjp2-7
        - graphviz
      brew:
        - openjpeg
      yum:
        - openssl-devel
        - freetype-devel
        - libpng-devel
        - libffi-devel
        - python-devel

    envs:
      - macos: py38
        name: py38_test

      - windows: py37
        name: py37_test

      - linux: py39-online
        name: py39_test_online

      - linux32: py38-32bit
        name: py38_test_32bit

      - linux: codestyle
        name: python_codestyle
        pytest: false

      - linux: py36-conda
        name: py36_conda
        libraries: {}

      - linux: py36-oldestdeps
        name: py36_test_oldestdeps

      - linux: py38-devdeps

      - linux: build_docs
        posargs: " "
        pytest: false

# On branches which aren't master, and not Pull Requests, build the wheels but only upload them on tags
- ${{ if and(ne(variables['Build.Reason'], 'PullRequest'), not(contains(variables['Build.SourceBranch'], 'master'))) }}:
  - template: publish.yml@OpenAstronomy
    parameters:
      # Only Upload to PyPI on tags
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
        pypi_connection_name : 'PyPI'
      test_extras: 'dev'
      test_command: 'pytest -p no:warnings --doctest-rst -m "not figure" --pyargs sunpy'
      submodules: false

      targets:
        - wheels_cp3[6789]-manylinux*x86_64
        - wheels_cp3[6789]-macosx*
        - sdist
      dependsOn:
        - py36_conda
        - py36_test_oldestdeps
        - py37_test
        - py38_test
        - py38_test_32bit
        - py39_test_online
