name: Changelog Bot

on:
  pull_request_target:
    types: [opened, reopened, edited, labeled, unlabeled]
    branches:
      - main

env:
  BOT_AUTHOR: 'SunPyBot <bot@sunpy.org>'

jobs:
  update-changelog:
    if: "!contains(github.event.pull_request.labels.*.name, 'No Changelog Entry Needed')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      - name: Setup Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Find and write changelog
        run: python tools/write_changelog_entry.py
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_BODY: ${{ github.event.pull_request.body }}
      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add changelog
          add_options: '-A'
          file_pattern: 'changelog/*.rst'
          commit_author: ${{ env.BOT_AUTHOR }}
