name: Build and publish

on:
  push:
    tags:
      - 'v*'
      - '!*dev*'
      - '!*pre*'
      - '!*post*'
  pull_request:
    branches:
      - 'main'
#    paths:
#      - '.github/workflows/publish.yml'
  # Allow manual runs through the web UI
  workflow_dispatch:

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@main
    with:
      test_extras: 'dev'
      test_command: 'pytest -p no:warnings --doctest-rst -m "not mpl_image_compare" --pyargs sunpy'
      submodules: false
      targets: |
        - cp3{8,9,10}-manylinux*_x86_64
        - cp3{8,9,10}-macosx_x86_64
        - cp3{8,9,10}-macosx_universal2
#    secrets:
#      pypi_password: ${{ secrets.pypi_password }}
