name: Build and publish

on:
  push:
    branches-ignore:
      - 'main'
      - '*backport*'
    tags:
      - 'v*'
    tags-ignore:
      - '*dev*'
      - '*pre*'
      - '*post*'
  pull_request:
    paths:
      - '.github/workflows/publish.yml'
  # Allow manual runs through the web UI
  workflow_dispatch:
  schedule:
    #        ┌───────── minute (0 - 59)
    #        │ ┌───────── hour (0 - 23)
    #        │ │ ┌───────── day of the month (1 - 31)
    #        │ │ │ ┌───────── month (1 - 12 or JAN-DEC)
    #        │ │ │ │ ┌───────── day of the week (0 - 6 or SUN-SAT)
    - cron: '0 3 * * *'  # Every day at 03:00 UTC

jobs:
  publish:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@main
    with:
      test_extras: 'dev'
      test_command: 'pytest -p no:warnings --doctest-rst -m "not mpl_image_compare" --pyargs sunpy'
      submodules: false
      targets: |
        - cp3{8,9,10}-manylinux*_x86_64
        - cp3{8,9,10}-macosx_x86_64
        - cp3{8,9,10}-macosx_universal2
#    secrets:
#      pypi_password: ${{ secrets.pypi_password }}
