name: Automated tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-remote-py39:
    uses: ./.github/workflows/python-test-workflow.yml
    with:
      os: ubuntu-latest
      python-version: '3.9'
      tox-env: py39-online
