name: Automated tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python-version: '3.9'
            tox-env: py39

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install system dependencies
      run: |
        sudo apt-get install -y libopenjp2-7 graphviz
        python -m pip install --upgrade pip
        python -m pip install tox tox-pypi-filter
    - name: Run tests
      run: |
        tox -e ${{ matrix.tox-env }} -- -n auto --dist loadgroup
