name: Automated tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux-tests:
    uses: dstansby/sunpy/.github/workflows/python-test-workflow.yml@gh-actions
    with:
      os: ubuntu-latest
      python-version: '3.9'
      tox-env: py39

  macosx-tests:
    uses: dstansby/sunpy/.github/workflows/python-test-workflow.yml@gh-actions
    with:
      os: macos-latest
      python-version: '3.8'
      tox-env: py38

  windows-tests:
    uses: dstansby/sunpy/.github/workflows/python-test-workflow.yml@gh-actions
    with:
      os: windows-latest
      python-version: '3.10'
      tox-env: py310

  remote-tests:
    needs: linux-tests
    uses: dstansby/sunpy/.github/workflows/python-test-workflow.yml@gh-actions
    with:
      os: ubuntu-latest
      python-version: '3.8'
      tox-env: py38-online
